-- ---------------------------------------------------------------------------------
-- one_time_payments: close public access, and keep the legacy Make.com webhook
-- off rows generated by Recurring Payments.
--
-- 1. ACCESS
--    The table has never had RLS, and the original schema granted ALL to `anon`
--    and `authenticated`. The Supabase publishable key ships in the browser
--    bundle, so anyone could read every Company's one-time payments, or insert
--    one against any Team Member and have the next invoice run bill it. Same
--    hole invoice_adjustments had (20260806000000).
--
--    Nothing legitimate uses those grants: every read and write goes through the
--    Next.js API on supabaseAdmin (service role, bypasses RLS). The SPA, the
--    legacy edge functions and shoreline-finance never query this table
--    directly, and it has no Realtime subscribers. If Clients should ever read
--    it directly, add a SELECT policy scoped through team_members.company_id —
--    do not re-grant writes.
--
-- 2. MAKE.COM WEBHOOK
--    A legacy webhook trigger POSTs every inserted row to a Make.com
--    scenario. Recurring Payments now insert one row per pay period, which would
--    repeat that for every period of every stipend. The trigger is narrowed to
--    one-time payments with a WHEN clause rather than dropped, because whatever
--    consumes that scenario isn't visible from this repo.
--
--    It is found by what it calls (supabase_functions.http_request), not by
--    name — the name differs between environments — and rebuilt from
--    pg_get_triggerdef so the URL and arguments actually deployed are kept.
--    Where no such trigger exists, nothing happens.
--
-- Requires 20260927000000 (recurring_payment_id).
-- ---------------------------------------------------------------------------------

BEGIN;

-- 1. Access ------------------------------------------------------------------------
ALTER TABLE public.one_time_payments ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.one_time_payments FROM anon, authenticated;

-- 2. Make.com webhook ----------------------------------------------------------------
DO $$
DECLARE
  r record;
  found int := 0;
BEGIN
  -- Matched on what the trigger does (a supabase_functions.http_request
  -- webhook on this table), not on its name: the name differs between
  -- environments (staging has "One_Time_Payments_Notification", the 2025
  -- snapshot "One Time Payments Notification").
  FOR r IN
    SELECT t.tgname, pg_get_triggerdef(t.oid) AS def
    FROM pg_trigger t
    WHERE t.tgrelid = 'public.one_time_payments'::regclass
      AND NOT t.tgisinternal
      AND pg_get_triggerdef(t.oid) ILIKE '%supabase_functions.http_request%'
  LOOP
    found := found + 1;

    IF r.def ILIKE '% WHEN (%' THEN
      RAISE NOTICE 'Webhook trigger % already has a WHEN clause; leaving it: %', r.tgname, r.def;
      CONTINUE;
    END IF;

    IF position(' EXECUTE FUNCTION ' IN r.def) = 0 THEN
      RAISE EXCEPTION 'Unexpected definition for webhook trigger %, not rewriting it: %', r.tgname, r.def;
    END IF;

    EXECUTE format('DROP TRIGGER %I ON public.one_time_payments', r.tgname);
    EXECUTE replace(
      r.def,
      ' EXECUTE FUNCTION ',
      ' WHEN (NEW.recurring_payment_id IS NULL) EXECUTE FUNCTION '
    );
    RAISE NOTICE 'Narrowed webhook trigger % to non-recurring rows', r.tgname;
  END LOOP;

  IF found = 0 THEN
    RAISE NOTICE 'No webhook trigger on one_time_payments; nothing to narrow';
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

COMMIT;

-- ---------------------------------------------------------------------------------
-- ROLLBACK (run manually if needed — Supabase migrations are forward-only).
-- Re-granting reopens the hole described above; only do it if something turns
-- out to depend on direct access.
--
--   BEGIN;
--   ALTER TABLE public.one_time_payments DISABLE ROW LEVEL SECURITY;
--   GRANT ALL ON public.one_time_payments TO anon, authenticated;
--   -- Webhook: recreate from pg_get_triggerdef without the WHEN clause.
--   NOTIFY pgrst, 'reload schema';
--   COMMIT;
-- ---------------------------------------------------------------------------------
